from django.urls import path
from projeto6 import views

urlpatterns = [
    path(
        'projeto06/channels/carregar-dados',
        views.ChannelAPIView.as_view(),
        name='channels-carregar-dados',
    ),
    path(
        'projeto06/deliveries/carregar-dados',
        views.DeliveryAPIView.as_view(),
        name='deliveries-carregar-dados',
    ),
    path(
        'projeto06/drivers/carregar-dados',
        views.DriverAPIView.as_view(),
        name='drivers-carregar-dados',
    ),
    path(
        'projeto06/hubs/carregar-dados',
        views.HubAPIView.as_view(),
        name='hubs-carregar-dados',
    ),
    path(
        'projeto06/orders/carregar-dados',
        views.OrderAPIView.as_view(),
        name='orders-carregar-dados',
    ),
    path(
        'projeto06/payments/carregar-dados',
        views.PaymentAPIView.as_view(),
        name='payments-carregar-dados',
    ),
    path(
        'projeto06/stores/carregar-dados',
        views.StoreAPIView.as_view(),
        name='stores-carregar-dados',
    ),
    # QUESTÕES
    path(
        'projeto06/questoes/1',
        views.Questao01APIView.as_view(),
        name='projeto06-questao01',
    ),
    path(
        'projeto06/questoes/2',
        views.Questao02APIView.as_view(),
        name='projeto06-questao02',
    ),
    path(
        'projeto06/questoes/3',
        views.Questao03APIView.as_view(),
        name='projeto06-questao03',
    ),
    path(
        'projeto06/questoes/4',
        views.Questao04APIView.as_view(),
        name='projeto06-questao04',
    ),
    path(
        'projeto06/questoes/5',
        views.Questao05APIView.as_view(),
        name='projeto06-questao05',
    ),
    path(
        'projeto06/questoes/6',
        views.Questao06APIView.as_view(),
        name='projeto06-questao06',
    ),
    path(
        'projeto06/questoes/7',
        views.Questao07APIView.as_view(),
        name='projeto06-questao07',
    ),
    path(
        'projeto06/questoes/8',
        views.Questao08APIView.as_view(),
        name='projeto06-questao08',
    ),
    path(
        'projeto06/questoes/9',
        views.Questao09APIView.as_view(),
        name='projeto06-questao09',
    ),
    path(
        'projeto06/questoes/10',
        views.Questao10APIView.as_view(),
        name='projeto06-questao10',
    ),
    path(
        'projeto06/questoes/11',
        views.Questao11APIView.as_view(),
        name='projeto06-questao11',
    ),
    path(
        'projeto06/questoes/12',
        views.Questao12APIView.as_view(),
        name='projeto06-questao12',
    ),
    path(
        'projeto06/questoes/13',
        views.Questao13APIView.as_view(),
        name='projeto06-questao13',
    ),
    path(
        'projeto06/questoes/14',
        views.Questao14APIView.as_view(),
        name='projeto06-questao14',
    ),
    path(
        'projeto06/questoes/15',
        views.Questao15APIView.as_view(),
        name='projeto06-questao15',
    ),
    path(
        'projeto06/questoes/16',
        views.Questao16APIView.as_view(),
        name='projeto06-questao16',
    ),
    path(
        'projeto06/questoes/17',
        views.Questao17APIView.as_view(),
        name='projeto06-questao17',
    ),
    path(
        'projeto06/questoes/18',
        views.Questao18APIView.as_view(),
        name='projeto06-questao18',
    ),
    path(
        'projeto06/questoes/19',
        views.Questao19APIView.as_view(),
        name='projeto06-questao19',
    ),
    path(
        'projeto06/questoes/20',
        views.Questao20APIView.as_view(),
        name='projeto06-questao20',
    ),
]
