# Generated by Django 4.2.1 on 2023-05-18 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cp02Navios",
            new_name="Navios",
        ),
        migrations.AlterModelTable(
            name="navios",
            table="p01Navios",
        ),
    ]
