# Generated by Django 4.2.1 on 2023-05-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                ("channel_id", models.IntegerField(primary_key=True, serialize=False)),
                ("channel_name", models.CharField(max_length=50)),
                ("channel_type", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "p06Chanels",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                ("delivery_id", models.IntegerField(primary_key=True, serialize=False)),
                ("delivery_order_id", models.IntegerField()),
                ("driver_id", models.IntegerField()),
                ("delivery_distance_meters", models.IntegerField()),
                ("delivery_status", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "p06Deliveries",
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driver_id", models.IntegerField(primary_key=True, serialize=False)),
                ("driver_modal", models.CharField(max_length=50)),
                ("driver_type", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "p06Drivers",
            },
        ),
        migrations.CreateModel(
            name="Hub",
            fields=[
                ("hub_id", models.IntegerField(primary_key=True, serialize=False)),
                ("hub_name", models.CharField(max_length=100)),
                ("hub_city", models.CharField(max_length=100)),
                ("hub_state", models.CharField(max_length=100)),
                ("hub_latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("hub_longitude", models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                "db_table": "p06Hubs",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.IntegerField(primary_key=True, serialize=False)),
                ("store_id", models.IntegerField(null=True)),
                ("channel_id", models.IntegerField(null=True)),
                ("payment_order_id", models.IntegerField(null=True)),
                ("delivery_order_id", models.IntegerField(null=True)),
                ("order_status", models.CharField(max_length=100, null=True)),
                (
                    "order_amount",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_delivery_fee",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_delivery_cost",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("order_created_hour", models.IntegerField(null=True)),
                ("order_created_minute", models.IntegerField(null=True)),
                ("order_created_day", models.IntegerField(null=True)),
                ("order_created_month", models.IntegerField(null=True)),
                ("order_created_year", models.IntegerField(null=True)),
                ("order_moment_created", models.DateTimeField(null=True)),
                ("order_moment_accepted", models.DateTimeField(null=True)),
                ("order_moment_ready", models.DateTimeField(null=True)),
                ("order_moment_collected", models.DateTimeField(null=True)),
                ("order_moment_in_expedition", models.DateTimeField(null=True)),
                ("order_moment_delivering", models.DateTimeField(null=True)),
                ("order_moment_delivered", models.DateTimeField(null=True)),
                ("order_moment_finished", models.DateTimeField(null=True)),
                (
                    "order_metric_collected_time",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_metric_paused_time",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_metric_production_time",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_metric_walking_time",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_metric_expediton_speed_time",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_metric_transit_time",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "order_metric_cycle_time",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
            ],
            options={
                "db_table": "p06Orders",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("payment_id", models.IntegerField(primary_key=True, serialize=False)),
                ("payment_order_id", models.IntegerField(null=True)),
                (
                    "payment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "payment_fee",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("payment_method", models.CharField(max_length=50, null=True)),
                ("payment_status", models.CharField(max_length=100, null=True)),
            ],
            options={
                "db_table": "p06Paymtns",
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("store_id", models.IntegerField(primary_key=True, serialize=False)),
                ("hub_id", models.IntegerField(null=True)),
                ("store_name", models.CharField(max_length=100)),
                ("store_segment", models.CharField(max_length=100)),
                (
                    "store_plan_price",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("store_latitude", models.IntegerField(null=True)),
                ("store_longitude", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "p06Stores",
            },
        ),
    ]
