# Generated by Django 4.2.1 on 2023-05-19 00:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto6", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="driver_id",
        ),
    ]
