# Generated by Django 4.2.1 on 2023-05-26 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto6', '0003_delivery_driver_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='p06Payments',
        ),
    ]
