# Generated by Django 4.2.1 on 2023-05-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto6', '0005_alter_order_order_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='channel',
            table='p06Channels',
        ),
    ]
