# Generated by Django 4.2.1 on 2023-05-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atleta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("noc", models.CharField(max_length=255, null=True)),
                ("discipline", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "cp04Atletas",
            },
        ),
        migrations.CreateModel(
            name="Medalha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Rank", models.IntegerField(null=True)),
                ("team_noc", models.CharField(max_length=255, null=True)),
                ("gold", models.IntegerField(null=True)),
                ("silver", models.IntegerField(null=True)),
                ("bronze", models.IntegerField(null=True)),
                ("total", models.IntegerField(null=True)),
                ("rank_by_total", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "cp04Medalhas",
            },
        ),
        migrations.CreateModel(
            name="Registro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discipline", models.CharField(max_length=255, null=True)),
                ("female", models.IntegerField(null=True)),
                ("male", models.IntegerField(null=True)),
                ("total", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "cp04Registros",
            },
        ),
        migrations.CreateModel(
            name="Time",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("discipline", models.CharField(max_length=255, null=True)),
                ("noc", models.CharField(max_length=255, null=True)),
                ("event", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "cp04Times",
            },
        ),
        migrations.CreateModel(
            name="Treinador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("noc", models.CharField(max_length=255, null=True)),
                ("discipline", models.CharField(max_length=255, null=True)),
                ("event", models.CharField(max_length=255, null=True)),
            ],
            options={
                "db_table": "cp04Treinadores",
            },
        ),
    ]
