# Generated by Django 4.2.1 on 2023-05-11 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto4", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medalha",
            old_name="Rank",
            new_name="rank",
        ),
    ]
