# Generated by Django 4.2.1 on 2023-05-11 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("projeto3", "0002_alter_pedido_data_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="data_pedido",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
