# Generated by Django 4.2.1 on 2023-05-11 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projeto3", "0003_alter_pedido_data_pedido"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="id_cliente",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="projeto3.clinete",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="id_vendedor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="projeto3.vendedor",
            ),
        ),
    ]
