# Generated by Django 4.2.1 on 2023-05-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto3", "0004_alter_pedido_id_cliente_alter_pedido_id_vendedor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clinete",
            name="id",
        ),
        migrations.RemoveField(
            model_name="pedido",
            name="id",
        ),
        migrations.RemoveField(
            model_name="vendedor",
            name="id",
        ),
        migrations.AlterField(
            model_name="clinete",
            name="id_cliente",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="id_pedido",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vendedor",
            name="id_vendedor",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
