# Generated by Django 4.2.1 on 2023-05-11 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto3", "0006_mymodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="myModel",
        ),
    ]
