# Generated by Django 4.2.1 on 2023-05-11 19:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto3", "0007_delete_mymodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Clinete",
            new_name="Cliente",
        ),
    ]
