# Generated by Django 4.2.1 on 2023-05-18 17:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto2", "0002_cancermamaoutfile"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cancermama",
            table="p02CancerMama",
        ),
        migrations.AlterModelTable(
            name="cancermamaoutfile",
            table="p02CancerMamaNovoDataset",
        ),
    ]
