# Generated by Django 4.2.1 on 2023-05-15 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_cliente", models.IntegerField(null=True)),
                ("nome_cliente", models.CharField(max_length=50, null=True)),
                ("endereco_cliente", models.CharField(max_length=50, null=True)),
                ("cidade_cliente", models.CharField(max_length=50, null=True)),
                ("estado_cliente", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "cp05Clientes",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_pedido", models.IntegerField(null=True)),
                ("id_cliente", models.IntegerField(null=True)),
                ("id_vendedor", models.IntegerField(null=True)),
                (
                    "data_pedido",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                ("id_entrega", models.IntegerField(null=True)),
                (
                    "valor_pedido",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
            ],
            options={
                "db_table": "cp05Pedidos",
            },
        ),
        migrations.CreateModel(
            name="Vendedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_vendedor", models.IntegerField(null=True)),
                ("nome_vendedor", models.CharField(null=True, verbose_name=50)),
                ("dept_vendedor", models.CharField(max_length=50, null=True)),
            ],
            options={
                "db_table": "cp05Vendedores",
            },
        ),
    ]
