# Generated by Django 4.2.1 on 2023-05-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto5", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PedidoResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "managed": False,
            },
        ),
    ]
