# Generated by Django 4.2.1 on 2023-05-17 00:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto5", "0002_pedidoresponse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PedidoResponse",
        ),
    ]
