# Generated by Django 4.2.1 on 2023-05-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projeto5", "0003_delete_pedidoresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vendas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(null=True)),
                ("pais", models.CharField(max_length=45, null=True)),
                ("produto", models.CharField(max_length=45, null=True)),
                ("faturamento", models.IntegerField(null=True)),
            ],
        ),
    ]
