# Generated by Django 4.2.1 on 2023-05-18 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projeto5", "0004_vendas"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="vendas",
            table="cp05Vendas",
        ),
    ]
